apiVersion: v1
kind: Pod
metadata:
  name: "{{ include "dubai-ml.fullname" . }}-test-connection"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dubai-ml.labels" . | nindent 4 }}
    helm.sh/hook: test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['--spider', 'http://{{ include "dubai-ml.serviceName" . }}:{{ .Values.service.port }}/health']
  restartPolicy: Never
