apiVersion: v1
kind: Service
metadata:
  name: {{ include "dubai-ml.serviceName" . }}
  labels:
    {{- include "dubai-ml.labels" . | nindent 4 }}
    app: dubai-realestate-ml
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "dubai-ml.selectorLabels" . | nindent 4 }}
    app: dubai-realestate-ml
    version: {{ .Values.activeVersion }}  
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
